/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Mar 30, 2010, 6:14:42 AM
 */

package movieTheater;

import javax.swing.JTextArea;

/**
 *
 * @author Loai Ghoraba
 */
public class Output extends javax.swing.JFrame {

    /** Creates new form Main */
    public Output() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arrivedArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        chosedArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        leavedArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        startedArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        thrownArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        arrivedArea.setColumns(20);
        arrivedArea.setRows(5);
        arrivedArea.setName("arrivedArea"); // NOI18N
        jScrollPane1.setViewportView(arrivedArea);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        chosedArea.setColumns(20);
        chosedArea.setRows(5);
        chosedArea.setName("chosedArea"); // NOI18N
        jScrollPane2.setViewportView(chosedArea);

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        leavedArea.setColumns(20);
        leavedArea.setRows(5);
        leavedArea.setName("leavedArea"); // NOI18N
        jScrollPane5.setViewportView(leavedArea);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        startedArea.setColumns(20);
        startedArea.setRows(5);
        startedArea.setName("startedArea"); // NOI18N
        jScrollPane4.setViewportView(startedArea);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        thrownArea.setColumns(20);
        thrownArea.setRows(5);
        thrownArea.setName("thrownArea"); // NOI18N
        jScrollPane3.setViewportView(thrownArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public static Semaphore print=new Semaphore(1);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arrivedArea;
    private javax.swing.JTextArea chosedArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea leavedArea;
    private javax.swing.JTextArea startedArea;
    private javax.swing.JTextArea thrownArea;
    // End of variables declaration//GEN-END:variables
    public JTextArea getArrivedArea()
    {
        return arrivedArea;
    }
    public JTextArea getChosedArea()
    {
        return chosedArea;
    }
    public JTextArea getStartedArea()
    {
        return startedArea;
    }
    public JTextArea getLeavedArea()
    {
        return leavedArea;
    }
    public JTextArea getThrownArea()
    {
        return thrownArea;
    }
}
